---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: set variables
      set_fact:
        cobbler_state: absent
        cobbler_inventory_state: absent
        cobbler_add_remove_state: absent
        ansible_var_files_state: absent
      tags:
        - never
        - destroy

    - import_role: 
        name: cobbler
      tags:
        - create

    - import_role: 
        name: cobbler_inventory
      tags:
        - create

    - import_role: 
        name: cobbler_add_remove
      tags:
        - always
        
    - import_role:
        name: ansible_var_files
      tags:
        - always
      
    - import_role: 
        name: cobbler_inventory
      tags:
        - never
        - destroy
        
    - import_role: 
        name: cobbler
      tags:
        - never
        - destroy
