---
- hosts: master

  tasks:
  - name: set host_key_checking to false
    become: yes
    ini_file:
      path: /etc/ansible/ansible.cfg
      section: defaults
      option: host_key_checking
      value: False

  - name: add nodes to /etc/hosts
    become: yes
    blockinfile:
      path: /etc/hosts
      block: |
        192.168.56.111  web1.example.com        web1
        192.168.56.112  web2.example.com        web2
        192.168.56.121  db1.example.com         db1
        192.168.56.122  db2.example.com         db2

  - name: install python-netaddr
    become: yes
    apt:
      name: python-netaddr
